### ISSUE TITLE
Where is jar?

### ISSUE THREAD

**Issue by cartals** [manami-project/manami#28]
I cannot find it.

**Comment by frykauf** [comment]
Can't either. Either nuked project or old readme. Don't know what to do.

**Comment by frykauf** [comment]
Bored and looked for it and it looks like dev had wanted travis ci to push manami.jar builds to github but didn't set it up properly. I hope he fixes it since I'm looking around for something to manage my anime library automatically too. (also on macOS)

https://travis-ci.org/github/manami-project/manami/builds
https://codecov.io/gh/manami-project/manami/branch/development/commits

**Comment by manami-project** [comment]
Hi @cartals,
thank you for your interest in this project.
There are currently some issues so that you pretty much cannot use it properly. That's why I removed the *.jar.

I haven't planned to fix anything in the java code anymore. Instead I want to reimplement this tool in kotlin. This will take time however.
If you need a tool fast then checkout the [anime topic](https://github.com/manami-project/manami/issues/28). There should be other tools like this.

I will at least update the README.md I guess.
